import { createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import { cookies } from "next/headers";
import { ADMIN_PASSWORD_HASH, verifyPassword } from "./credentials";
import { sessionSecret } from "./secrets";
import type { Kv } from "./store";

/*
  Admin: one password exchanged for a signed, HttpOnly session cookie. The password is
  MASTIHA_ADMIN_PASSWORD when set, otherwise the one whose hash is in credentials.ts; the
  signing key is generated by the server (secrets.ts). Guests: each conversation gets a
  random token that only the guest's browser holds; the server stores its SHA-256.
*/

export const ADMIN_COOKIE = "mls_admin";
const SESSION_DAYS = 30;

const sha256 = (value: string) => createHash("sha256").update(value).digest();
const safeEqual = (a: Buffer, b: Buffer) => a.length === b.length && timingSafeEqual(a, b);
const configuredPassword = () => {
  const password = process.env.MASTIHA_ADMIN_PASSWORD ?? "";
  return password.length >= 8 ? password : null;
};

export async function passwordMatches(input: string): Promise<boolean> {
  const configured = configuredPassword();
  if (configured) return safeEqual(sha256(input), sha256(configured));
  return verifyPassword(input, ADMIN_PASSWORD_HASH);
}

async function sessionKey(kv: Kv): Promise<Buffer> {
  // Changing the password signs every device out.
  return createHmac("sha256", await sessionSecret(kv)).update(`session:${configuredPassword() ?? ADMIN_PASSWORD_HASH}`).digest();
}

const sign = (payload: string, key: Buffer) => createHmac("sha256", key).update(payload).digest("base64url");

export async function createSession(kv: Kv): Promise<{ value: string; maxAge: number }> {
  const maxAge = SESSION_DAYS * 24 * 60 * 60;
  const payload = `${Date.now() + maxAge * 1000}.${randomBytes(12).toString("base64url")}`;
  return { value: `${payload}.${sign(payload, await sessionKey(kv))}`, maxAge };
}

export async function sessionValid(kv: Kv, value: string | undefined): Promise<boolean> {
  if (!value) return false;
  const parts = value.split(".");
  if (parts.length !== 3) return false;
  const payload = `${parts[0]}.${parts[1]}`;
  if (!safeEqual(Buffer.from(parts[2]), Buffer.from(sign(payload, await sessionKey(kv))))) return false;
  return Number(parts[0]) > Date.now();
}

export async function isAdmin(kv: Kv): Promise<boolean> {
  return sessionValid(kv, (await cookies()).get(ADMIN_COOKIE)?.value);
}

export function newGuestToken(): { token: string; hash: string } {
  const token = randomBytes(32).toString("base64url");
  return { token, hash: sha256(token).toString("hex") };
}

export function guestTokenMatches(request: Request, hash: string): boolean {
  const token = request.headers.get("authorization")?.match(/^Bearer ([\w-]{20,100})$/)?.[1];
  return Boolean(token && hash) && safeEqual(sha256(token!), Buffer.from(hash, "hex"));
}
