// The host's inbox at /admin. Greek by default, with English available.

const el = {
  brand: "Mastiha",
  title: "Συνομιλίες",
  filters: { open: "Ανοιχτές", closed: "Κλειστές", all: "Όλες" },
  search: "Αναζήτηση ονόματος ή μηνύματος",
  empty: "Δεν υπάρχουν συνομιλίες ακόμα.",
  emptyHint: "Όταν ένας επισκέπτης πατήσει «Μιλήστε με την Αθηνά», η συζήτηση θα εμφανιστεί εδώ και θα λάβετε ειδοποίηση.",
  select: "Επιλέξτε μια συνομιλία από τη λίστα.",
  guest: "Επισκέπτης",
  online: "Συνδεδεμένος τώρα",
  seen: "Τελευταία φορά {time}",
  writesIn: "Γράφει στα {language}",
  languages: { el: "ελληνικά", en: "αγγλικά", tr: "τουρκικά" },
  started: "Ξεκίνησε {time}",
  close: "Κλείσιμο συζήτησης",
  reopen: "Άνοιγμα ξανά",
  remove: "Διαγραφή",
  confirmRemove: "Να διαγραφεί οριστικά αυτή η συζήτηση;",
  reply: "Γράψτε την απάντησή σας…",
  send: "Αποστολή",
  back: "Πίσω",
  logout: "Αποσύνδεση",
  sound: "Ήχος",
  notifications: {
    enable: "Ειδοποιήσεις στη συσκευή",
    on: "Ειδοποιήσεις ενεργές",
    unsupported: "Αυτός ο browser δεν υποστηρίζει ειδοποιήσεις.",
    blocked: "Οι ειδοποιήσεις είναι μπλοκαρισμένες στις ρυθμίσεις του browser.",
    missing: "Οι ειδοποιήσεις push δεν έχουν ρυθμιστεί στον server.",
    ios: "Στο iPhone: πατήστε Κοινοποίηση → «Προσθήκη στην οθόνη Αφετηρίας» και ανοίξτε την εφαρμογή από εκεί.",
  },
  names: { guest: "Επισκέπτης", host: "Εσείς", bot: "Αυτόματος βοηθός" },
  system: {
    handoff: "Ο επισκέπτης ζήτησε να μιλήσει μαζί σας",
    closed: "Κλείσατε τη συζήτηση",
    reopened: "Η συζήτηση άνοιξε ξανά",
  },
  failed: "Δεν στάλθηκε · πατήστε για επανάληψη",
  newMessage: "Νέο μήνυμα",
  offline: "Χωρίς σύνδεση. Προσπαθούμε ξανά…",
  login: {
    title: "Είσοδος",
    body: "Οι συνομιλίες με τους επισκέπτες του Mastiha Luxury Suites.",
    password: "Κωδικός",
    submit: "Είσοδος",
    wrong: "Λάθος κωδικός.",
    busy: "Πολλές προσπάθειες. Δοκιμάστε ξανά σε λίγα λεπτά.",
    error: "Κάτι πήγε στραβά. Δοκιμάστε ξανά.",
  },
  setup: {
    title: "Η ζωντανή συνομιλία δεν έχει ενεργοποιηθεί ακόμα",
    body: "Μέχρι να ενεργοποιηθεί, οι επισκέπτες βλέπουν τον αυτόματο βοηθό και συνδέσμους για Airbnb και Booking.com.",
  },
  time: { now: "τώρα", minutes: "{n} λεπ.", hours: "{n} ώρ.", yesterday: "χθες" },
};

export type AdminCopy = typeof el;
export type AdminLocale = "el" | "en";

const en: AdminCopy = {
  brand: "Mastiha",
  title: "Conversations",
  filters: { open: "Open", closed: "Closed", all: "All" },
  search: "Search names or messages",
  empty: "No conversations yet.",
  emptyHint: "When a guest taps “Talk to Athina”, the conversation appears here and you get a notification.",
  select: "Choose a conversation from the list.",
  guest: "Guest",
  online: "Online now",
  seen: "Last seen {time}",
  writesIn: "Writes in {language}",
  languages: { el: "Greek", en: "English", tr: "Turkish" },
  started: "Started {time}",
  close: "Close conversation",
  reopen: "Reopen",
  remove: "Delete",
  confirmRemove: "Delete this conversation permanently?",
  reply: "Write your reply…",
  send: "Send",
  back: "Back",
  logout: "Sign out",
  sound: "Sound",
  notifications: {
    enable: "Notifications on this device",
    on: "Notifications on",
    unsupported: "This browser doesn’t support notifications.",
    blocked: "Notifications are blocked in the browser settings.",
    missing: "Push notifications aren’t configured on the server.",
    ios: "On iPhone: tap Share → “Add to Home Screen” and open the app from there.",
  },
  names: { guest: "Guest", host: "You", bot: "Automated assistant" },
  system: {
    handoff: "The guest asked to talk to you",
    closed: "You closed the conversation",
    reopened: "Conversation reopened",
  },
  failed: "Not sent · tap to retry",
  newMessage: "New message",
  offline: "Offline. Retrying…",
  login: {
    title: "Sign in",
    body: "Conversations with Mastiha Luxury Suites guests.",
    password: "Password",
    submit: "Sign in",
    wrong: "Wrong password.",
    busy: "Too many attempts. Try again in a few minutes.",
    error: "Something went wrong. Please try again.",
  },
  setup: {
    title: "Live chat isn’t switched on yet",
    body: "Until it is, guests see the automated assistant and links to Airbnb and Booking.com.",
  },
  time: { now: "now", minutes: "{n} min", hours: "{n} h", yesterday: "yesterday" },
};

export const ADMIN_COPY: Record<AdminLocale, AdminCopy> = { el, en };
