// The host's portal at /admin. Greek by default, with English available.

const el = {
  brand: "Mastiha",
  property: "Mastiha Luxury Suites",
  place: "Βροντάδος · Χίος",
  workroom: "Διαχείριση",
  views: {
    desk: "Κέντρο ελέγχου",
    needs: "Χρειάζονται εσάς",
    all: "Όλες οι συζητήσεις",
    bot: "Με τον βοηθό",
    closed: "Ολοκληρωμένες",
    settings: "Ρυθμίσεις",
  },
  groups: { conversations: "Συζητήσεις", manage: "Διαχείριση" },
  rail: { collapse: "Σύμπτυξη μενού", expand: "Ανάπτυξη μενού", open: "Άνοιγμα μενού", close: "Κλείσιμο μενού" },
  site: "Η ιστοσελίδα",
  notice: "Οι συζητήσεις σβήνονται αυτόματα 30 ημέρες μετά το τελευταίο μήνυμα.",
  live: "Ζωντανά",
  offline: "Χωρίς σύνδεση. Προσπαθούμε ξανά…",
  greeting: { morning: "Καλημέρα, Αθηνά", afternoon: "Καλησπέρα, Αθηνά", evening: "Καλησπέρα, Αθηνά" },
  desk: {
    eyebrow: "Επισκόπηση",
    metrics: { needs: "Περιμένουν απάντηση", today: "Σήμερα", month: "Τελευταίες 30 ημέρες", answered: "Απαντήσεις βοηθού σήμερα" },
    recent: "Πρόσφατες συζητήσεις",
    seeAll: "Όλες οι συζητήσεις",
    empty: "Δεν υπάρχουν ακόμα συζητήσεις.",
    assistant: "Αυτόματος βοηθός",
    assistantTitle: "Απαντά στους επισκέπτες όλο το 24ωρο.",
    assistantBody: "Απαντά μόνο με όσα γράφει η ιστοσελίδα. Ό,τι δεν ξέρει, ή όταν το ζητήσει ο επισκέπτης, έρχεται σε εσάς με ειδοποίηση.",
    assistantOn: "Ενεργός",
    assistantOff: "Απαντά μόνο με έτοιμες απαντήσεις",
    model: "Μοντέλο",
    free: "Δωρεάν κλήσεις που απομένουν σήμερα",
    sources: { ai: "Από το μοντέλο", cache: "Από αποθηκευμένες απαντήσεις", guide: "Έτοιμες απαντήσεις", fallback: "Έτοιμες απαντήσεις (το μοντέλο δεν απάντησε)" },
    open: "Δείτε τις συζητήσεις του βοηθού",
  },
  list: {
    search: "Αναζήτηση ονόματος ή μηνύματος",
    empty: { needs: "Καμία συζήτηση δεν περιμένει απάντηση.", all: "Δεν υπάρχουν συζητήσεις.", bot: "Καμία συζήτηση με τον βοηθό.", closed: "Καμία ολοκληρωμένη συζήτηση." },
    emptyHint: "Όταν ένας επισκέπτης ζητήσει να σας μιλήσει, η συζήτηση έρχεται εδώ και λαμβάνετε ειδοποίηση.",
    waiting: "Περιμένει",
    withBot: "Βοηθός",
    withHost: "Εσείς",
    closed: "Ολοκληρώθηκε",
  },
  thread: {
    select: "Επιλέξτε μια συζήτηση από τη λίστα.",
    back: "Πίσω",
    online: "Συνδεδεμένος τώρα",
    seen: "Τελευταία φορά {time}",
    language: "Γράφει στα {language}",
    languages: { el: "ελληνικά", en: "αγγλικά", tr: "τουρκικά" },
    takeOver: "Αναλαμβάνω εγώ",
    giveBack: "Επιστροφή στον βοηθό",
    close: "Ολοκλήρωση",
    reopen: "Άνοιγμα ξανά",
    remove: "Διαγραφή",
    confirmRemove: "Να διαγραφεί οριστικά αυτή η συζήτηση;",
    email: "Email",
    reply: "Γράψτε την απάντησή σας…",
    send: "Αποστολή",
    hint: "Ο επισκέπτης βλέπει την απάντησή σας αμέσως. Enter για αποστολή, Shift+Enter για νέα γραμμή.",
    botHint: "Ο βοηθός απαντά σε αυτή τη συζήτηση. Αν γράψετε, την αναλαμβάνετε εσείς.",
    latest: "Στο τελευταίο μήνυμα",
    failed: "Δεν στάλθηκε · πατήστε για επανάληψη",
    sources: { ai: "μοντέλο", cache: "αποθηκευμένη απάντηση", guide: "έτοιμη απάντηση" },
  },
  names: { guest: "Επισκέπτης", host: "Εσείς", bot: "Βοηθός" },
  system: {
    handoff: "Ο επισκέπτης ζήτησε να σας μιλήσει",
    takeover: "Αναλάβατε τη συζήτηση",
    returned: "Η συζήτηση επέστρεψε στον βοηθό",
    closed: "Η συζήτηση ολοκληρώθηκε",
    reopened: "Η συζήτηση άνοιξε ξανά",
  },
  settings: {
    title: "Ρυθμίσεις",
    notifications: "Ειδοποιήσεις",
    notificationsBody: "Λαμβάνετε ειδοποίηση στο κινητό όταν ένας επισκέπτης ζητήσει να σας μιλήσει ή σας γράψει.",
    enable: "Ενεργοποίηση ειδοποιήσεων",
    disable: "Απενεργοποίηση",
    on: "Οι ειδοποιήσεις είναι ενεργές σε αυτή τη συσκευή.",
    off: "Οι ειδοποιήσεις είναι ανενεργές σε αυτή τη συσκευή.",
    unsupported: "Αυτός ο browser δεν υποστηρίζει ειδοποιήσεις.",
    blocked: "Οι ειδοποιήσεις είναι μπλοκαρισμένες στις ρυθμίσεις του browser.",
    missing: "Οι ειδοποιήσεις δεν είναι διαθέσιμες αυτή τη στιγμή.",
    ios: "Στο iPhone: πατήστε Κοινοποίηση → «Προσθήκη στην οθόνη Αφετηρίας» και ανοίξτε την εφαρμογή από εκεί.",
    sound: "Ήχος για νέα μηνύματα",
    soundBody: "Ένα απαλό καμπανάκι όσο η σελίδα είναι ανοιχτή.",
    language: "Γλώσσα",
    retention: "Διατήρηση δεδομένων",
    retentionBody: "Κάθε συζήτηση σβήνεται αυτόματα 30 ημέρες μετά το τελευταίο μήνυμα. Μπορείτε να διαγράψετε μια συζήτηση και νωρίτερα.",
    assistant: "Αυτόματος βοηθός",
    assistantBody: "Δωρεάν μοντέλα μέσω OpenRouter, μόνο από παρόχους που δεν κρατούν και δεν χρησιμοποιούν όσα γράφουν οι επισκέπτες. Αν δεν απαντήσουν, απαντά ο ίδιος ο βοηθός με τις έτοιμες απαντήσεις της ιστοσελίδας.",
    logout: "Αποσύνδεση",
    on_: "Ναι",
    off_: "Όχι",
  },
  newMessage: "Νέο μήνυμα",
  login: {
    title: "Είσοδος",
    body: "Οι συζητήσεις με τους επισκέπτες του Mastiha Luxury Suites.",
    password: "Κωδικός",
    submit: "Είσοδος",
    wrong: "Λάθος κωδικός.",
    busy: "Πολλές προσπάθειες. Δοκιμάστε ξανά σε λίγα λεπτά.",
    error: "Κάτι πήγε στραβά. Δοκιμάστε ξανά.",
  },
  setup: {
    title: "Η βάση δεδομένων των συζητήσεων δεν έχει συνδεθεί ακόμα",
    body: "Μέχρι να συνδεθεί, ο αυτόματος βοηθός απαντά κανονικά στους επισκέπτες, αλλά οι συζητήσεις δεν αποθηκεύονται εδώ.",
  },
  time: { now: "τώρα", minutes: "{n} λεπ.", hours: "{n} ώρ.", yesterday: "χθες" },
};

export type AdminCopy = typeof el;
export type AdminLocale = "el" | "en";

const en: AdminCopy = {
  brand: "Mastiha",
  property: "Mastiha Luxury Suites",
  place: "Vrontados · Chios",
  workroom: "Admin",
  views: {
    desk: "Overview",
    needs: "Waiting for you",
    all: "All conversations",
    bot: "With the assistant",
    closed: "Resolved",
    settings: "Settings",
  },
  groups: { conversations: "Conversations", manage: "Manage" },
  rail: { collapse: "Collapse menu", expand: "Expand menu", open: "Open menu", close: "Close menu" },
  site: "The website",
  notice: "Conversations are deleted automatically 30 days after their last message.",
  live: "Live",
  offline: "Offline. Trying again…",
  greeting: { morning: "Good morning, Athina", afternoon: "Good afternoon, Athina", evening: "Good evening, Athina" },
  desk: {
    eyebrow: "Overview",
    metrics: { needs: "Waiting for a reply", today: "Today", month: "Last 30 days", answered: "Assistant replies today" },
    recent: "Recent conversations",
    seeAll: "All conversations",
    empty: "No conversations yet.",
    assistant: "Automated assistant",
    assistantTitle: "Answers guests around the clock.",
    assistantBody: "It only uses what the website says. Anything it doesn’t know, or whenever a guest asks, comes to you with a notification.",
    assistantOn: "Active",
    assistantOff: "Answering with ready-made replies only",
    model: "Model",
    free: "Free calls left today",
    sources: { ai: "From the model", cache: "From saved answers", guide: "Ready-made replies", fallback: "Ready-made replies (model didn’t answer)" },
    open: "See the assistant’s conversations",
  },
  list: {
    search: "Search names or messages",
    empty: { needs: "Nothing is waiting for a reply.", all: "No conversations.", bot: "No conversations with the assistant.", closed: "No resolved conversations." },
    emptyHint: "When a guest asks to talk to you, the conversation comes here and you get a notification.",
    waiting: "Waiting",
    withBot: "Assistant",
    withHost: "You",
    closed: "Resolved",
  },
  thread: {
    select: "Choose a conversation from the list.",
    back: "Back",
    online: "Online now",
    seen: "Last seen {time}",
    language: "Writes in {language}",
    languages: { el: "Greek", en: "English", tr: "Turkish" },
    takeOver: "Take over",
    giveBack: "Back to the assistant",
    close: "Resolve",
    reopen: "Reopen",
    remove: "Delete",
    confirmRemove: "Delete this conversation permanently?",
    email: "Email",
    reply: "Write your reply…",
    send: "Send",
    hint: "The guest sees your reply straight away. Enter to send, Shift+Enter for a new line.",
    botHint: "The assistant is answering this conversation. If you write, you take it over.",
    latest: "Latest message",
    failed: "Not sent · tap to retry",
    sources: { ai: "model", cache: "saved answer", guide: "ready-made reply" },
  },
  names: { guest: "Guest", host: "You", bot: "Assistant" },
  system: {
    handoff: "The guest asked to talk to you",
    takeover: "You took over the conversation",
    returned: "The conversation went back to the assistant",
    closed: "Conversation resolved",
    reopened: "Conversation reopened",
  },
  settings: {
    title: "Settings",
    notifications: "Notifications",
    notificationsBody: "Get a notification on your phone when a guest asks to talk to you or writes to you.",
    enable: "Turn on notifications",
    disable: "Turn off",
    on: "Notifications are on for this device.",
    off: "Notifications are off for this device.",
    unsupported: "This browser doesn’t support notifications.",
    blocked: "Notifications are blocked in the browser settings.",
    missing: "Notifications aren’t available right now.",
    ios: "On iPhone: tap Share → “Add to Home Screen” and open the app from there.",
    sound: "Sound for new messages",
    soundBody: "A soft chime while the page is open.",
    language: "Language",
    retention: "Data retention",
    retentionBody: "Every conversation is deleted automatically 30 days after its last message. You can delete one sooner.",
    assistant: "Automated assistant",
    assistantBody: "Free models through OpenRouter, only from providers that neither keep nor use what guests write. If they don’t answer, the assistant replies with the website’s ready-made answers.",
    logout: "Sign out",
    on_: "On",
    off_: "Off",
  },
  newMessage: "New message",
  login: {
    title: "Sign in",
    body: "Conversations with Mastiha Luxury Suites guests.",
    password: "Password",
    submit: "Sign in",
    wrong: "Wrong password.",
    busy: "Too many attempts. Try again in a few minutes.",
    error: "Something went wrong. Try again.",
  },
  setup: {
    title: "The conversation database isn’t connected yet",
    body: "Until it is, the assistant answers guests as usual, but conversations aren’t stored here.",
  },
  time: { now: "now", minutes: "{n} min", hours: "{n} h", yesterday: "yesterday" },
};

export const ADMIN_COPY: Record<AdminLocale, AdminCopy> = { el, en };
