export type StayLocale = "en" | "el" | "tr";
const en = {
  skip: "Skip to the suite", nav: "Explore the property", home: "Home", suite: "The suite", gallery: "Photographs", location: "Location", language: "Language", book: "Check availability", bookShort: "Book your stay", close: "Close", all: "All spaces", bedrooms: "Bedrooms", outdoors: "Outdoors", details: "Details", previous: "Previous photograph", next: "Next photograph",
  place: "Vrontados, Chios, Greece", heroLine: "A quieter side of Chios.", heroSmall: "Your own place on the island.", discover: "Discover Mastiha", filmEyebrow: "A walk through the apartment", filmTitle: "Come inside.", filmHint: "Scroll to explore", skipFilm: "Skip the film", filmFallback: "A glimpse inside the apartment", filmSteps: ["The living space", "A closer look", "Make yourself at home"],
  introEyebrow: "An entire home, entirely yours", introTitle: "Space for the way\nyou like to stay.", introBody: "A private home in Vrontados, with two bedrooms, a living room and space to settle into your own routine. Open the doors, make a coffee, and take Chios at your own pace.", areaLabel: "private space", guestsLabel: "guests", bedroomsLabel: "bedrooms", photoAction: "View photograph",
  roomsEyebrow: "The spaces", roomsTitle: "From morning light\nto lights out.", livingTitle: "A place to come together.", livingBody: "Coffee at the table. A quiet afternoon on the sofa. A living space to return to between days out on the island.", bedroomTitle: "Close the door on the day.", bedroomBody: "Two bedrooms, soft finishes and room to unpack. Take a closer look at each space before you arrive.",
  captions: { living: "Living room", master: "Main bedroom", second: "Second bedroom", bathroom: "Bathroom", terrace: "Terrace" },
  galleryEyebrow: "A closer look", galleryTitle: "Explore every space.", galleryBody: "The rooms, the terrace and the details. Open a photograph to browse the full collection.", galleryOpen: "Open the full gallery", galleryCount: "photographs", zoom: "Zoom in", zoomOut: "Zoom out", fullscreen: "Enter fullscreen", exitFullscreen: "Exit fullscreen", hideThumbs: "Hide thumbnails", showThumbs: "Show thumbnails",
  amenitiesEyebrow: "Part of the stay", amenitiesTitle: "The everyday,\ntaken care of.", amenitiesBody: "A kitchen for your own meals, coffee for the morning and the practical things that make a longer stay easier.", amenities: ["Private parking", "Wi-Fi", "Air conditioning", "Equipped kitchen", "Washing machine", "Smart TVs", "Outdoor seating", "Soundproof space"],
  outsideEyebrow: "Outside, a different pace", outsideTitle: "Take your coffee\noutside.", outsideBody: "A terrace for a slow start or a pause at the end of the day.",
  ratingsEyebrow: "Guest reviews", ratingsTitle: "Read it from our guests.", reviews: "reviews", ratingsNote: "Scores recorded {date}. See the booking platforms for current reviews.", readReviews: "Read reviews",
  locationEyebrow: "Vrontados, Chios", locationTitle: "The island starts\nat your doorstep.", locationBody: "The shoreline is approximately {distance} metres away. Plan your arrival using the map, and confirm the meeting point with your host.", maps: "Open Google Maps", directions: "Get directions", mapLoad: "Open the Google Map", mapNote: "Google loads only when you open the map. The pin is tied to the verified Google Place for Mastiha Luxury Suites.", mapTitle: "Mastiha Luxury Suites on Google Maps",
  faqEyebrow: "Before you arrive", faqTitle: "A few useful details.", faqs: [
    { q: "How many people can stay?", a: "The private home accommodates up to {guests} guests, with {bedrooms} bedrooms and {bathrooms} bathroom." },
    { q: "How do I make a reservation?", a: "Choose Airbnb or Booking.com. Your dates, final price, payment and cancellation terms are confirmed on the booking platform." },
    { q: "What are the arrival and departure times?", a: "Confirm check-in and check-out with the host through your reservation. This website does not override the terms of your booking." },
    { q: "Is parking available?", a: "Free private parking is listed for the property. Ask your host for the arrival instructions." }
  ], closing: "Make room\nfor Chios.", closingBody: "Find your dates on Airbnb or Booking.com.", bookingTitle: "Your stay starts here.", bookingBody: "Choose your booking platform to see live availability, prices and reservation terms.", privacy: "Privacy", registration: "Registration", top: "Back to top"
};
export type StayCopy = typeof en;
const el: StayCopy = {
  skip: "Μετάβαση στη διαμονή", nav: "Γνωρίστε το κατάλυμα", home: "Αρχική", suite: "Η διαμονή", gallery: "Φωτογραφίες", location: "Τοποθεσία", language: "Γλώσσα", book: "Διαθεσιμότητα", bookShort: "Κλείστε τη διαμονή σας", close: "Κλείσιμο", all: "Όλοι οι χώροι", bedrooms: "Υπνοδωμάτια", outdoors: "Εξωτερικά", details: "Λεπτομέρειες", previous: "Προηγούμενη φωτογραφία", next: "Επόμενη φωτογραφία",
  place: "Βροντάδος, Χίος, Ελλάδα", heroLine: "Μια πιο ήρεμη πλευρά της Χίου.", heroSmall: "Ο δικός σας χώρος στο νησί.", discover: "Γνωρίστε το Mastiha", filmEyebrow: "Μια βόλτα στο διαμέρισμα", filmTitle: "Περάστε μέσα.", filmHint: "Κυλήστε για περιήγηση", skipFilm: "Παράλειψη περιήγησης", filmFallback: "Μια ματιά στο διαμέρισμα", filmSteps: ["Το καθιστικό", "Μια πιο κοντινή ματιά", "Νιώστε σαν στο σπίτι σας"],
  introEyebrow: "Ένα σπίτι, αποκλειστικά δικό σας", introTitle: "Χώρος για τη διαμονή\nπου σας ταιριάζει.", introBody: "Ένα ιδιωτικό σπίτι στον Βροντάδο, με δύο υπνοδωμάτια, καθιστικό και χώρο για τον δικό σας ρυθμό. Ανοίξτε τις πόρτες, φτιάξτε έναν καφέ και γνωρίστε τη Χίο χωρίς βιασύνη.", areaLabel: "ιδιωτικός χώρος", guestsLabel: "επισκέπτες", bedroomsLabel: "υπνοδωμάτια", photoAction: "Προβολή φωτογραφίας",
  roomsEyebrow: "Οι χώροι", roomsTitle: "Από το πρωινό φως\nμέχρι την ξεκούραση.", livingTitle: "Χώρος για να βρεθείτε μαζί.", livingBody: "Καφές στο τραπέζι. Ένα ήσυχο απόγευμα στον καναπέ. Ένας χώρος για να επιστρέφετε ανάμεσα στις εξορμήσεις στο νησί.", bedroomTitle: "Αφήστε τη μέρα απέξω.", bedroomBody: "Δύο υπνοδωμάτια και χώρος για να τακτοποιηθείτε. Δείτε κάθε δωμάτιο πριν από την άφιξή σας.", captions: { living: "Καθιστικό", master: "Κύριο υπνοδωμάτιο", second: "Δεύτερο υπνοδωμάτιο", bathroom: "Μπάνιο", terrace: "Βεράντα" },
  galleryEyebrow: "Μια πιο κοντινή ματιά", galleryTitle: "Γνωρίστε κάθε χώρο.", galleryBody: "Τα δωμάτια, η βεράντα και οι λεπτομέρειες. Ανοίξτε μια φωτογραφία για να δείτε ολόκληρη τη συλλογή.", galleryOpen: "Δείτε όλες τις φωτογραφίες", galleryCount: "φωτογραφίες", zoom: "Μεγέθυνση", zoomOut: "Σμίκρυνση", fullscreen: "Πλήρης οθόνη", exitFullscreen: "Έξοδος πλήρους οθόνης", hideThumbs: "Απόκρυψη μικρογραφιών", showThumbs: "Εμφάνιση μικρογραφιών",
  amenitiesEyebrow: "Μέρος της διαμονής", amenitiesTitle: "Τα καθημερινά,\nφροντισμένα.", amenitiesBody: "Κουζίνα για τα γεύματά σας, καφές για το πρωί και όσα κάνουν μια μεγαλύτερη διαμονή ευκολότερη.", amenities: ["Ιδιωτικό πάρκινγκ", "Wi-Fi", "Κλιματισμός", "Εξοπλισμένη κουζίνα", "Πλυντήριο ρούχων", "Smart TV", "Εξωτερικό καθιστικό", "Ηχομόνωση"],
  outsideEyebrow: "Έξω, ένας άλλος ρυθμός", outsideTitle: "Πάρτε τον καφέ σας\nστη βεράντα.", outsideBody: "Για ένα ήρεμο ξεκίνημα ή μια παύση στο τέλος της ημέρας.", ratingsEyebrow: "Αξιολογήσεις επισκεπτών", ratingsTitle: "Διαβάστε τις εμπειρίες τους.", reviews: "αξιολογήσεις", ratingsNote: "Βαθμολογίες που καταγράφηκαν στις {date}. Δείτε τις τρέχουσες αξιολογήσεις στις πλατφόρμες.", readReviews: "Δείτε τις αξιολογήσεις",
  locationEyebrow: "Βροντάδος, Χίος", locationTitle: "Το νησί ξεκινά\nστην πόρτα σας.", locationBody: "Η ακτή βρίσκεται περίπου {distance} μέτρα μακριά. Σχεδιάστε την άφιξή σας με τον χάρτη και επιβεβαιώστε το σημείο συνάντησης με τον οικοδεσπότη.", maps: "Άνοιγμα Google Maps", directions: "Οδηγίες διαδρομής", mapLoad: "Άνοιγμα Google Map", mapNote: "Η Google φορτώνεται μόνο όταν ανοίξετε τον χάρτη. Η καρφίτσα συνδέεται με το επαληθευμένο Google Place του Mastiha Luxury Suites.", mapTitle: "Mastiha Luxury Suites στο Google Maps",
  faqEyebrow: "Πριν από την άφιξη", faqTitle: "Μερικές χρήσιμες λεπτομέρειες.", faqs: [
    { q: "Πόσα άτομα μπορούν να μείνουν;", a: "Το σπίτι φιλοξενεί έως {guests} επισκέπτες, με {bedrooms} υπνοδωμάτια και {bathrooms} μπάνιο." },
    { q: "Πώς κάνω κράτηση;", a: "Επιλέξτε Airbnb ή Booking.com. Οι ημερομηνίες, η τελική τιμή, η πληρωμή και οι όροι ακύρωσης επιβεβαιώνονται στην πλατφόρμα κράτησης." },
    { q: "Ποιες είναι οι ώρες άφιξης και αναχώρησης;", a: "Επιβεβαιώστε τις ώρες με τον οικοδεσπότη μέσα από την κράτησή σας. Ο ιστότοπος δεν αντικαθιστά τους όρους της κράτησης." },
    { q: "Υπάρχει πάρκινγκ;", a: "Στις παροχές αναφέρεται δωρεάν ιδιωτικό πάρκινγκ. Ζητήστε οδηγίες άφιξης από τον οικοδεσπότη." }
  ], closing: "Κάντε χώρο\nγια τη Χίο.", closingBody: "Βρείτε ημερομηνίες στο Airbnb ή στο Booking.com.", bookingTitle: "Η διαμονή σας ξεκινά εδώ.", bookingBody: "Επιλέξτε πλατφόρμα για την τρέχουσα διαθεσιμότητα, τις τιμές και τους όρους κράτησης.", privacy: "Απόρρητο", registration: "Αριθμός μητρώου", top: "Στην αρχή"
};
const tr: StayCopy = {
  skip: "Konaklamaya geç", nav: "Evi keşfedin", home: "Ana sayfa", suite: "Konaklama", gallery: "Fotoğraflar", location: "Konum", language: "Dil", book: "Müsaitlik", bookShort: "Konaklamanızı ayırtın", close: "Kapat", all: "Tüm alanlar", bedrooms: "Yatak odaları", outdoors: "Dış alan", details: "Ayrıntılar", previous: "Önceki fotoğraf", next: "Sonraki fotoğraf",
  place: "Vrontados, Sakız Adası, Yunanistan", heroLine: "Sakız Adası'nın daha sakin bir yüzü.", heroSmall: "Adada size ait bir yer.", discover: "Mastiha'yı keşfedin", filmEyebrow: "Dairede bir gezinti", filmTitle: "İçeri buyurun.", filmHint: "Keşfetmek için kaydırın", skipFilm: "Gezintiyi atla", filmFallback: "Daireye bir bakış", filmSteps: ["Yaşam alanı", "Daha yakından", "Kendinizi evinizde hissedin"],
  introEyebrow: "Tamamen size ait bir ev", introTitle: "Kendi ritminizde\nkonaklayın.", introBody: "Vrontados'ta iki yatak odası ve bir oturma odası bulunan özel bir ev. Kapıları açın, kahvenizi hazırlayın ve Sakız Adası'nı kendi ritminizde keşfedin.", areaLabel: "özel alan", guestsLabel: "misafir", bedroomsLabel: "yatak odası", photoAction: "Fotoğrafı görüntüle",
  roomsEyebrow: "Alanlar", roomsTitle: "Sabah ışığından\ngece huzuruna.", livingTitle: "Bir araya gelmek için.", livingBody: "Masada kahve, kanepede sakin bir öğleden sonra. Adadaki gezileriniz arasında dönebileceğiniz bir yaşam alanı.", bedroomTitle: "Günü geride bırakın.", bedroomBody: "İki yatak odası ve yerleşmek için alan. Gelmeden önce her odaya daha yakından bakın.", captions: { living: "Oturma odası", master: "Ana yatak odası", second: "İkinci yatak odası", bathroom: "Banyo", terrace: "Teras" },
  galleryEyebrow: "Daha yakından", galleryTitle: "Her alanı keşfedin.", galleryBody: "Odalar, teras ve ayrıntılar. Tüm koleksiyonu görmek için bir fotoğrafı açın.", galleryOpen: "Tüm fotoğrafları görüntüle", galleryCount: "fotoğraf", zoom: "Yakınlaştır", zoomOut: "Uzaklaştır", fullscreen: "Tam ekrana geç", exitFullscreen: "Tam ekrandan çık", hideThumbs: "Küçük resimleri gizle", showThumbs: "Küçük resimleri göster",
  amenitiesEyebrow: "Konaklamaya dahil", amenitiesTitle: "Günlük ihtiyaçlar,\ndüşünülmüş.", amenitiesBody: "Yemekleriniz için mutfak, sabah kahvesi ve daha uzun bir konaklamayı kolaylaştıran ihtiyaçlar.", amenities: ["Özel otopark", "Wi-Fi", "Klima", "Donanımlı mutfak", "Çamaşır makinesi", "Smart TV", "Dış mekan oturma alanı", "Ses yalıtımı"],
  outsideEyebrow: "Dışarıda başka bir ritim", outsideTitle: "Kahvenizi\nterasa taşıyın.", outsideBody: "Güne sakin başlamak veya akşam bir mola vermek için.", ratingsEyebrow: "Misafir yorumları", ratingsTitle: "Misafirlerimizden okuyun.", reviews: "yorum", ratingsNote: "Puanlar {date} tarihinde kaydedildi. Güncel yorumlar için rezervasyon platformlarını ziyaret edin.", readReviews: "Yorumları okuyun",
  locationEyebrow: "Vrontados, Sakız Adası", locationTitle: "Ada kapınızın\nönünde başlar.", locationBody: "Sahil yaklaşık {distance} metre uzaklıktadır. Haritadan gelişinizi planlayın ve buluşma noktasını ev sahibinizle doğrulayın.", maps: "Google Maps'i aç", directions: "Yol tarifi", mapLoad: "Google haritasını aç", mapNote: "Google yalnızca haritayı açtığınızda yüklenir. İşaretçi, Mastiha Luxury Suites'in doğrulanmış Google Place kaydına bağlıdır.", mapTitle: "Google Maps'te Mastiha Luxury Suites",
  faqEyebrow: "Gelmeden önce", faqTitle: "Birkaç yararlı bilgi.", faqs: [
    { q: "Kaç kişi kalabilir?", a: "Ev en fazla {guests} misafir ağırlayabilir; {bedrooms} yatak odası ve {bathrooms} banyo bulunur." },
    { q: "Nasıl rezervasyon yapabilirim?", a: "Airbnb veya Booking.com'u seçin. Tarihler, toplam fiyat, ödeme ve iptal koşulları rezervasyon platformunda onaylanır." },
    { q: "Giriş ve çıkış saatleri nedir?", a: "Saatleri rezervasyonunuz üzerinden ev sahibiyle doğrulayın. Bu site rezervasyon koşullarının yerine geçmez." },
    { q: "Otopark var mı?", a: "Tesisin olanakları arasında ücretsiz özel otopark bulunur. Geliş talimatları için ev sahibinize danışın." }
  ], closing: "Sakız Adası'na\nyer açın.", closingBody: "Airbnb veya Booking.com'da tarihlerinizi bulun.", bookingTitle: "Konaklamanız burada başlıyor.", bookingBody: "Güncel müsaitlik, fiyatlar ve koşullar için rezervasyon platformunuzu seçin.", privacy: "Gizlilik", registration: "Kayıt", top: "Başa dön"
};
export function getStayCopy(locale: string): StayCopy { return ({ en, el, tr } as Record<string, StayCopy>)[locale] ?? en; }
export function normalizeStayLocale(locale: string): StayLocale { return locale === "el" || locale === "tr" ? locale : "en"; }
export function fillCopy(value: string, values: Record<string, string | number>): string { return value.replace(/\{(\w+)\}/g, (_, key: string) => String(values[key] ?? `{${key}}`)); }
