import Link from 'next/link';
import { setRequestLocale } from 'next-intl/server';
import { normalizeStayLocale, getStayCopy } from '@/content/stay-copy';
import { propertyData } from '@/content/property';
import { localeMetadata } from '@/lib/site';
export async function generateMetadata({params}:{params:Promise<{locale:string}>}) {return localeMetadata((await params).locale,true);}
const texts={
 en:['This website presents Mastiha Luxury Suites. It has no booking payment form, guest account or newsletter form.','The hosting provider processes technical request information such as IP addresses for delivery and security. This website’s interaction events stay in the browser; no analytics collection service is currently connected in the application.','Photographs are served by this website. Google Maps is contacted only after you choose to load the map. You can instead use the external directions link. Google and the reservation platforms apply their own privacy terms when you visit them.','Reservations and their personal data are handled on Airbnb or Booking.com, not by a payment system on this website. For questions about your data or a reservation, contact the host through the Airbnb listing.'],
 el:['Αυτός ο ιστότοπος παρουσιάζει το Mastiha Luxury Suites. Δεν διαθέτει φόρμα πληρωμής κράτησης, λογαριασμό επισκέπτη ή φόρμα newsletter.','Ο πάροχος φιλοξενίας επεξεργάζεται τεχνικά στοιχεία αιτημάτων, όπως διευθύνσεις IP, για την παροχή και την ασφάλεια της υπηρεσίας. Τα συμβάντα αλληλεπίδρασης παραμένουν στον browser· στην εφαρμογή δεν έχει συνδεθεί υπηρεσία συλλογής analytics.','Οι φωτογραφίες σερβίρονται από τον ιστότοπό μας. Η Google Maps φορτώνεται μόνο όταν επιλέξετε την προβολή του χάρτη. Εναλλακτικά, υπάρχει εξωτερικός σύνδεσμος οδηγιών. Η Google και οι πλατφόρμες κρατήσεων εφαρμόζουν τους δικούς τους όρους απορρήτου όταν τις επισκέπτεστε.','Οι κρατήσεις και τα προσωπικά δεδομένα τους διαχειρίζονται στο Airbnb ή στο Booking.com, όχι σε σύστημα πληρωμών αυτού του ιστοτόπου. Για ερωτήσεις σχετικά με δεδομένα ή κράτηση, επικοινωνήστε με την οικοδέσποινα μέσω της καταχώρισης του Airbnb.'],
 tr:['Bu site Mastiha Luxury Suites’i tanıtır. Rezervasyon ödeme formu, misafir hesabı veya bülten formu içermez.','Barındırma sağlayıcısı, hizmet sunumu ve güvenlik için IP adresleri gibi teknik istek bilgilerini işler. Etkileşim olayları tarayıcıda kalır; uygulamaya şu anda bir analitik toplama hizmeti bağlı değildir.','Fotoğraflar bu siteden sunulur. Google Maps yalnızca haritayı yüklemeyi seçtiğinizde açılır. Bunun yerine dış yol tarifi bağlantısını kullanabilirsiniz. Google ve rezervasyon platformlarında kendi gizlilik koşulları geçerlidir.','Rezervasyonlar ve ilgili kişisel veriler bu sitenin ödeme sistemi üzerinden değil, Airbnb veya Booking.com üzerinde işlenir. Verileriniz veya rezervasyonunuzla ilgili sorular için Airbnb ilanı üzerinden ev sahibiyle iletişime geçin.'],
};
export default async function PrivacyPage({params}:{params:Promise<{locale:string}>}) {
 const {locale}=await params, lang=normalizeStayLocale(locale);setRequestLocale(lang);const c=getStayCopy(lang);
 return <main style={{minHeight:'100svh',background:'#fff',color:'#252729',padding:'80px max(24px,7vw)'}}><div style={{maxWidth:760,margin:'auto'}}><Link href={`/${lang}`}>← Mastiha Luxury Suites</Link><h1 style={{fontFamily:'var(--font-display), var(--font-sans), sans-serif',fontWeight:450,letterSpacing:'-.035em',fontSize:'clamp(38px,6vw,64px)',margin:'40px 0 24px'}}>{c.privacy}</h1>{texts[lang].map(text=><p key={text} style={{lineHeight:1.85,marginBottom:24}}>{text}</p>)}<a href={propertyData.bookingLinks.airbnb} target="_blank" rel="noopener noreferrer">Airbnb ↗</a><p style={{fontSize:12,marginTop:40}}>2026-09-21 · {c.registration} {propertyData.licenseNumber}</p></div></main>;
}
